### ISSUE TITLE
Fix: Support older OpenCL version 1.1

### ISSUE THREAD

**Issue by L3P3** [tigrazone/smallptgpu1.6#1]
When I ran this app on my HD 5850, supporting only OpenCL 1.1, I got compilation errors complaining about some features not supported. However, they are actually available after setting a flag and now, the demo runs perfectly with my old card.

I added this line below `#define GPU_KERNEL` in rendering_kernel.cl and rendering_kernel_dl.cl:
```
#pragma OPENCL EXTENSION cl_clang_storage_class_specifiers : enable
```

**Comment by tigrazone** [comment]
thank you!
